### PR TITLE
simplified ModuleLoader

### PR DESCRIPTION
**Pull request by fidransky**
I simplified `ModuleLoader` to load modules directly from classpath instead of special directory. Modules are added to classpath as any other maven dependencies using `pom.xml` which makes them easily managable too.

Additionally, modules use classpath of the main application which makes it possible to load `config.json` from the resources folder.

Please, check if it matches your vision of how it should work. Functionality is unchanged.

### CODE REVIEW

**Comment by fidransky** [comment]
Simplified even more using [Java's native SPI](https://www.baeldung.com/java-spi).

**Comment by tomasSimandl** [comment]
Your simplification absolutely destroy possibility to update, create, or delete plugins in runtime.

**Comment by tomasSimandl** [comment]
First of all I don't understand why was necessary to completely rewrite my code. 

My last comment is probably not true. With SPI is possible load modules in runtime (probably)

Module functionality isn't complete and i am not sure if this solution can be used for it.
1) upload page will by modified for every module. This will be probably created by loading own form from module (not fully decided yet).
2) calling plugin for graph update (like was in cocaex with CRCE for changing incompatible modules)

**Comment by fidransky** [comment]
Don't get insulted, it's just a proposal (that's why I created pull request). Your solution works perfectly fine but it seemed like reinventing the wheel to me. I think we should use native language features where possible. On top of that, it was a great opportunity to learn something new for me.

Feel free to leave this PR open. If it shows up as a preferable solution in the future, it's here.

**Comment by tomasSimandl** [comment]
The main requirement was to be able to load modules at runtime or at least without recompilation of the project. With this solution is necessary for every plugin to change pom.xml and compile the project.
If you can modify this solution to be possible to load modules at run time, I am happy to use it.

**Comment by fidransky** [comment]
Runtime module loading works now. I ended up with solution similar to your original one but using SPI which makes some things a lot more straightforward. The greatest benefit is that a module *must* implement the `IModule` interface now so all its methods are guaranteed to be there.

About 

> is necessary for every plugin to change pom.xml

\- that's not really true. You can still add the module during runtime to `lib/` folder manually. The dependency in pom.xml is just for developer's convenience so that we dont have to copy the jar manually all the time.

I believe the final solution takes the best from both of our approaches.

**Pull request merged**
